// Generated by CoffeeScript 1.10.0
subjects["文系2年(1)"] = ["#f99", "1Q,Tue,56"];

subjects["文系2年(2)"] = ["#f99", "1Q,Fri,56"];

subjects["文系2年(3)"] = ["#f99", "2Q,Mon,12"];

subjects["文系2年(4)"] = ["#f99", "2Q,Thu,12"];

subjects["文系3年(1)"] = ["#f99", "1Q,Tue,78"];

subjects["文系3年(2)"] = ["#f99", "1Q,Fri,78"];

subjects["文系3年(3)"] = ["#f99", "2Q,Mon,34"];

subjects["文系3年(4)"] = ["#f99", "2Q,Wed,34"];
