// Generated by CoffeeScript 1.10.0
subjects["label:情報工学科200"] = [];

subjects["プログラミング第一E"] = ["#cff", "1Q,Thu,56", "2Q,Thu,56"];

subjects["確率と統計E"] = ["#cff", "1Q,Thu,78", "2Q,Thu,78"];

subjects["情報実験第一E"] = ["#cff", "1Q,Mon,56", "1Q,Mon,78", "2Q,Mon,56", "2Q,Mon,78"];

subjects["フーリエ変換とラプラス変換E"] = ["#cff", "1Q,Fri,78", "2Q,Tue,78"];

subjects["論理回路理論E"] = ["#cff", "2Q,Tue,56", "2Q,Fri,12", "2Q,Fri,34"];

subjects["プログラミング第一O"] = ["#cff", "1Q,Mon,56", "2Q,Mon,56"];

subjects["確率と統計O"] = ["#cff", "1Q,Mon,78", "2Q,Mon,78"];

subjects["情報実験第一O"] = ["#cff", "1Q,Thu,56", "1Q,Thu,78", "2Q,Thu,56", "2Q,Thu,78"];

subjects["フーリエ変換とラプラス変換O"] = ["#cff", "1Q,Fri,78", "2Q,Tue,78"];

subjects["論理回路理論O"] = ["#cff", "2Q,Tue,56", "2Q,Fri,12", "2Q,Fri,34"];

subjects["label:情報工学科300"] = [];

subjects["離散構造とアルゴリズムE"] = ["#9cc", "1Q,Mon,56", "1Q,Fri,56", "2Q,Fri,56", "2Q,Fri,78"];

subjects["代数系と符号理論E"] = ["#9cc", "1Q,Thu,34", "1Q,Fri,56", "2Q,Tue,78", "2Q,Fri,56"];

subjects["情報実験第三E"] = ["#9cc", "1Q,Mon,12", "1Q,Mon,34", "1Q,Fri,34", "2Q,Mon,12", "2Q,Mon,34", "2Q,Fri,34"];

subjects["関数解析学E"] = ["#9cc", "1Q,Tue,56", "2Q,Tue,56"];

subjects["プログラミング第三E"] = ["#9cc", "1Q,Tue,34", "2Q,Tue,34"];

subjects["人工知能基礎E"] = ["#9cc", "1Q,Thu,12", "2Q,Thu,12"];

subjects["計算機アーキテクチャ第一E"] = ["#9cc", "1Q,Thu,78", "2Q,Thu,56"];

subjects["離散構造とアルゴリズムO"] = ["#9cc", "1Q,Mon,34", "1Q,Fri,56", "2Q,Tue,78", "2Q,Fri,56"];

subjects["代数系と符号理論O"] = ["#9cc", "1Q,Thu,78", "1Q,Fri,56", "2Q,Fri,56", "2Q,Fri,78"];

subjects["情報実験第三O"] = ["#9cc", "1Q,Tue,34", "1Q,Thu,12", "1Q,Thu,34", "2Q,Tue,34", "2Q,Thu,12", "2Q,Thu,34"];

subjects["関数解析学O"] = ["#9cc", "1Q,Mon,12", "2Q,Mon,12"];

subjects["プログラミング第三O"] = ["#9cc", "1Q,Tue,56", "2Q,Tue,56"];

subjects["人工知能基礎O"] = ["#9cc", "1Q,Fri,34", "2Q,Fri,34"];

subjects["計算機アーキテクチャ第一O"] = ["#9cc", "1Q,Mon,56", "2Q,Mon,56"];

subjects["集積回路設計"] = ["#9cc", "1Q,Thu,56", "2Q,Thu,78"];

subjects["信号処理"] = ["#9cc", "1Q,Tue,12", "2Q,Tue,12"];

subjects["ディジタル通信"] = ["#9cc", "1Q,Mon,78", "2Q,Mon,78"];

subjects["計算機ネットワーク"] = ["#9cc", "1Q,Tue,78", "2Q,Tue,78"];
