// Generated by CoffeeScript 1.10.0
subjects["label:情報工学系200"] = [];

subjects["計算基礎論E"] = ["#99f", "1Q,Tue,78", "1Q,Fri,12", "1Q,Fri,34"];

subjects["計算基礎論O"] = ["#99f", "1Q,Tue,78", "1Q,Fri,12", "1Q,Fri,34"];

subjects["label:情報工学系300"] = [];

subjects["コンパイラ構成"] = ["#66c", "1Q,Tue,12", "2Q,Tue,12"];

subjects["先端情報工学"] = ["#66c", "1Q,Fri,56", "2Q,Fri,56"];
