// Generated by CoffeeScript 1.10.0
subjects["label:情報工学系200"] = [];

subjects["計算基礎論E"] = ["#99f", ["W935", "1Q,Tue,78"], ["W935", "1Q,Fri,12"], ["W935", "1Q,Fri,34"]];

subjects["計算基礎論O"] = ["#99f", ["W934", "1Q,Tue,78"], ["W934", "1Q,Fri,12"], ["W934", "1Q,Fri,34"]];

subjects["label:情報工学系300"] = [];

subjects["コンパイラ構成"] = ["#66c", ["W933", "1Q,Tue,12"], ["W933", "2Q,Tue,12"]];

subjects["先端情報工学"] = ["#66c", ["W933", "1Q,Fri,56"], ["W933", "2Q,Fri,56"]];
